---
- name: Conditional Playbook
  hosts: 34.213.84.73
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: take input
      package: 
        name: "{{package}}"
        state: latest   
