---
- name: My first playbook
  hosts: all
  become: true
  become_method: sudo 
  user: centos
  tasks: 
  - name: install package
    package:  
      name: httpd 
      state: present

#  - name: Install Telnet
#    package: 
#      name: telnet
#      state: installed

 